### ISSUE TITLE
PHP 5.5 & newest?

### ISSUE THREAD

**Issue by lazyest** [deranjer/OpenVPN-PHP-Management-Gui#12]
Just checked with old Debian6 - its working from scratch but with 8.0 is compeletely wrong. Is project abandoned or possible to take a quick look to adopt it for current Debian/Ubuntu?

**Comment by deranjer** [comment]
Unfortunately, I don't plan on working on this any longer.  You are free to fork it or if you submit pull requests I can still merge them, but that is the extent of my work on this from now on (unless I get a ton of time on my hands)
